server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/coursesdb
  application:
    name: business-courses-v1
  redis:
    host: 172.17.0.1 #localhost #192.168.0.102
    port: 6379
    ttl:
      seconds: 60

logging:
  level:
    org.springframework.data.mongodb.core: DEBUG
