server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/coursesdb #connection to mongo db
  application:
    name: business-courses-v1
  redis:
    host: 172.17.0.1 #using docker ip for connect to redis container
    port: 6379 #port redis container
    ttl:
      seconds: 60 #after this time the data will be delete

logging:
  level:
    org.springframework.data.mongodb.core: DEBUG
